EXEC DBO.Zync 'i Elsa/ElsaWorkflowDefinitions.sql';
EXEC DBO.Zync 'i Elsa/ElsaWorkflowInstances.sql';
EXEC DBO.Zync 'i Elsa/ElsaActivityInstances.sql';
EXEC DBO.Zync 'i Elsa/ElsaBookmarks.sql';
EXEC DBO.Zync 'i Elsa/ElsaWorkflowExecutionLogRecords.sql';
EXEC DBO.Zync 'i Elsa/ElsaLabels.sql';
EXEC DBO.Zync 'i Elsa/ElsaWorkflowDefinitionLabels.sql';
EXEC DBO.Zync 'i Elsa/ElsaStoredBookmarks.sql';
EXEC DBO.Zync 'i Elsa/ElsaIndexes.sql';
