EXEC DBO.Zync 'i Base/BaseUsers.sql';
EXEC DBO.Zync 'i Base/BaseUsersAttributes.sql';
EXEC DBO.Zync 'i Base/BaseRoles.sql';
EXEC DBO.Zync 'i Base/BaseActivityLog.sql';
EXEC DBO.Zync 'i Base/BaseUsersRoles.sql';
EXEC DBO.Zync 'i Base/BaseRolesAttributes.sql';
EXEC DBO.Zync 'i Base/BasePersons.sql';
EXEC DBO.Zync 'i Base/BaseInfo.sql';
EXEC DBO.Zync 'i Base/BaseSeedData.sql';
