/*
Generated by GenerateZyncPackageFromDb.ps1 on 2025-09-28 00:21
Package: Base
*/
EXEC DBO.Zync 'i Base/BaseUser.sql';
EXEC DBO.Zync 'i Base/BaseUserAttribute.sql';
EXEC DBO.Zync 'i Base/BaseRole.sql';
EXEC DBO.Zync 'i Base/BaseActivityLog.sql';
EXEC DBO.Zync 'i Base/BaseUserRole.sql';
EXEC DBO.Zync 'i Base/BaseRolesAttributes.sql';
EXEC DBO.Zync 'i Base/BasePerson.sql';
EXEC DBO.Zync 'i Base/BaseInfo.sql';
